version: '3.4'

services:
  Users.Api:
    image: users.api
    build:
      context: .
      dockerfile: Users.Api/Dockerfile
    depends_on:
      - rabbit

  loggerservice:
    image: loggerservice
    build:
      context: .
      dockerfile: LoggerService/Dockerfile
    depends_on:
      - rabbit
      
  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    container_name: rabbit
    #expose:
      #- 15672/TCP
      #- 5671/TCP
      #- 15671/TCP
      #- 5672/TCP
      #- 4369/TCP

    ports:
      - "15672:15672"
      - "5671:5671"
      - "15671:15671"
      - "5672:5672"
      - "4369:4369"

    