version: '3.4'

services:
  Users.Api:
    image: users.api
    build:
      context: .
      dockerfile: Users.Api/Dockerfile
    depends_on:
      - rabbit
    links: 
        - rabbit:rabbitmq
     
  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    container_name: rabbit
    expose:
      - 5672

    ports:
      - "15672:15672"
      - "127.0.0.1:5671:5671"
      - "15671:15671"
      - "127.0.0.1:5672:5672"
      - "4369:4369"

    
  consumerapp:
    image: ${DOCKER_REGISTRY}consumerapp
    build:
      context: .
      dockerfile: ConsumerApp/Dockerfile
    links: 
        - rabbit:rabbitmq

